### ISSUE TITLE
AS.3: Data QC and versioning standards

### ISSUE THREAD

**Issue by jmcmurry** [TranslatorIIPrototypes/operations#2]
**Issue Description:**
Coordinate a consensus protocol for long-term data quality control and data updates. In addition to Translator-wide standardization, the API will include QA/QC services. There will be a weekly/monthly/daily quality check of data and tests of services using standard protocols, and a defined versioning system.

**Comment by tursynay** [comment]
*Issue Description:*
Coordinate a consensus protocol for long-term data quality control and data updates. In addition to Translator-wide standardization, the API will include QA/QC services. There will be a weekly/monthly/daily quality check of data and tests of services using standard protocols, and a defined versioning system.

**Comment by tursynay** [comment]
moved to new org: https://github.com/TranslatorSRI/Operations/issues/9
