### ISSUE TITLE
TS.7: Extend equivalence API to handle complex path matches and semantic similarity

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#21]
**Issue Description:**
The segment 1 equivalence API will return equivalent or exact match CURIEs. In segment 2 we will return entities that have more complex relationships. We will extend the equivalence API and return the full logical structure or graph that captures the relationship. We will also implement generic semantic similarity.

**Comment by tursynay** [comment]
Hi Kent,

I am assigning this issue to you, please let me know if you think there should be another person this issue should be assigned to.

Thank you,

Tursynay

**Comment by kshefchek** [comment]
Sounds good! I assume this will be a part of https://github.com/TranslatorIIPrototypes/NodeNormalization? @cbizon and @PhillipsOwen curious your thoughts on how to approach this

**Comment by tursynay** [comment]
moved to the new location: https://github.com/TranslatorSRI/Operations/issues/27
