### ISSUE TITLE
AS 1.1. Guidelines for federation vs. integration to help Translator teams efficiently divide labor.

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#22]
AS.1 breakdown task

**Comment by diatomsRcool** [comment]
Initial documentation for what is the purview of individual teams vs committees vs working groups is contained in the governance document and the charters for the Committees and working groups. This will be reviewed and updated annually.

**Comment by tursynay** [comment]
moved to new org: https://github.com/TranslatorSRI/Operations/issues
