### ISSUE TITLE
AS 1.3. Language of discourse for user-facing API for Translator operations

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#24]

**Comment by diatomsRcool** [comment]
This is a task for the Architecture Committee.

**Comment by diatomsRcool** [comment]
This has been specified [here](https://github.com/NCATSTranslator/TranslatorArchitecture).

**Comment by tursynay** [comment]
moved to new org: https://github.com/TranslatorSRI/Operations
