### ISSUE TITLE
AS 1.5.  API standards that define the interfaces used for interoperability between KPs, ARAs, the ARS, and other services

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#26]

**Comment by diatomsRcool** [comment]
This is a task for the Architecture Committee.

**Comment by diatomsRcool** [comment]
This is specified [here](https://github.com/NCATSTranslator/TranslatorArchitecture).

**Comment by tursynay** [comment]
moved to new org: https://github.com/TranslatorSRI/Operations/issues
