### ISSUE TITLE
Update org members

### ISSUE THREAD

**Issue by nlharris** [TranslatorIIPrototypes/operations#30]
The people list for this org, https://github.com/orgs/TranslatorIIPrototypes/people, needs to be updated. It seems to include a subset of Translator (or just Translator SRI?) but with some people I don't recognize, and it's missing many current SRI team members (such as Tom Conlin and Matt Brush).

I don't have permission to change the people list. @jzollars do you?

**Comment by tursynay** [comment]
@nlharris, I got permissions to add people from Julie. I can try changing your role in the org. I will update the people with the current list of SRI team.

**Comment by nlharris** [comment]
Thanks, Tursynay!

**Comment by cbizon** [comment]
In retrospect, adding this repo to this org was probably not the right thing to do. This org was set up to handle different renci repos in the prototype phase of translator.  That's where all the 'extra' people are coming from.  I'm thinking we should just make an SRI org and put operations, and possibly other things, in there.

**Comment by nlharris** [comment]
Agreed, that would be cleaner. Do you want to start the new SRI org?

**Comment by cbizon** [comment]
I have made TranslatorSRI and invited the 3 of you - once you accept I'll give you permissions and you all can figure out the rest of the list...

**Comment by tursynay** [comment]
Thank you, Chris. I will move all issues here and close this repo

**Comment by tursynay** [comment]
Invited the SRI team members to the new org that Chris created: https://github.com/orgs/TranslatorSRI/people
