### ISSUE TITLE
AS.5: Provide documentation portal 

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#4]
**Issue Description:**

Develop a documentation website and structure to allow KP/ARA owners to easily add their own documentation

**Comment by jmcmurry** [comment]
@cmungall  and @diatomsRcool  can you clarify what venue you were hoping for? GH pages? RTD? Something else? I think some of the [workflow from CD2H guidebook](https://github.com/data2health/reusable-data-best-practices/blob/master/README.md) could be repurposed, but please advise. It is a Y1 activity so we should get on this soon. cc: @mellybelly.

**Comment by jmcmurry** [comment]
Also cc: @RichardBruskiewich since this might be part of his remit.

**Comment by RichardBruskiewich** [comment]
Roger that @jmcmurry !

I generally agree that the [workflow from CD2H guidebook](https://github.com/data2health/reusable-data-best-practices/blob/master/README.md) looks promising and could perhaps be copied and quickly adapted.

Just a point of information: alas, @cmungall is awaiting the SRI funds via OSU, before LBL can commit an SRI subcontract to me. I'm certainly willing to spend a few hours here and there to get my bearings on this task, but the heavy lifting will have to await signing of the contract, and a triage review of the work with you all about the relative priorities of the SRI work to be done.

**Comment by cmungall** [comment]
I have the same Q as @jmcmurry. I would opt for simplest thing possible, e.g. GH pages or RTD. It must use GH as CMS

I don't think this is your top priorty @RichardBruskiewich

**Comment by diatomsRcool** [comment]
second GH

**Comment by RichardBruskiewich** [comment]
@tursynay you can also co-assign kbruskiewicz to this issue as well.

**Comment by tursynay** [comment]
moved to the new org: https://github.com/TranslatorSRI/Operations/issues/11
