### ISSUE TITLE
BL.1: BioLink community review and requirements

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#5]
**Issue Description:**
Review the BioLink model with the ARAs and KPs to ensure that it meets the needs of Translator. Make plans for the addition of any missing components.

**Comment by tursynay** [comment]
Hi Anne, 

does this make sense to assign to you? 

Thanks,

Tursynay

**Comment by diatomsRcool** [comment]
Yes, I can take this on. I will need help identifying the appropriate contact and scheduling meetings tho.

**Comment by diatomsRcool** [comment]
What's the deadline on this?

**Comment by tursynay** [comment]
Hi Anne, checked with Julie. Here is the list of folks to involve:

Deepak Unni (must have)
Kent Shefchek (must have)
Richard Bruskiewich* (must have)
Melissa Haendel (if possible)
Chris Mungall (if possible)
Tursynay Issabekova (?)
Matt Brush
Nomi Harris
Karamarie Fecho*

As for the due date, I guess it was listed as to be ~~done~~ started in Y1b (March - April 2020). 

~~Would July 30 be reasonable?~~

Let me know if there is anything I can assist you with this task.

**Comment by diatomsRcool** [comment]
Task started....

**Comment by diatomsRcool** [comment]
https://docs.google.com/spreadsheets/d/1WDkqNMhy7aer_3-JB4SCVhp1MZeFYZjCnYuRCnoZguo/edit#gid=1750114328

**Comment by nlharris** [comment]
@diatomsRcool and I discussed this today; we have a plan.

**Comment by tursynay** [comment]
Hi @nlharris and @diatomsRcool, I can edit out the date. the date is there from a while ago when I was sorting through the milestones and it was not clear at the time that the milestone was a start date not necessarily a date when we should achieve a certain thing. I crossed it out. What is the plan?

**Comment by nlharris** [comment]
The proposal (Anne is checking with Matt Brush about this): add to Matt’s spreadsheet a “Biolink Mapping” column to each of the KP tabs, and the relevant ARA tabs, to list which Biolink property matches the requirement.

It looks like Matt Brush (mbrush) needs to be added to the GitHub team (https://github.com/orgs/TranslatorIIPrototypes/people) -- @tursynay do you have permission to do that?

**Comment by tursynay** [comment]
@nlharris, @mbrush has been invited to the org

**Comment by tursynay** [comment]
moved to the new org: https://github.com/TranslatorSRI/Operations/issues/12
